version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
      - save_cache:
          key: "walz_module"
          paths: 
            - src/walz_module

  test:
    docker:
      - image: circleci/node:13.8.0
    - checkout
    - restore_cache:
        key: "walz_module"
    - run: npm i
    - run: npm run test

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm audit

workflow:
  my-workflow:
    jobs:
      - build
      - test:
          requires: build
      - analyze:
          requires: test